### ISSUE TITLE
Is it possible to write the cases to EXCEL?

### ISSUE THREAD

**Issue by ArayofEntropy** [dianxiangxu/MISTA#1]
I wanner if there is a API doc or other docs so I can learn this tool much deeper.

**Comment by samerkhamaiseh** [comment]
Yes, if you access to http://cs.boisestate.edu/~dxu/research/MBT.html, you
will find the documents you need about MISTA. moreover, The source code
file of MISTA has the documentations of using MISTA.

**Comment by samerkhamaiseh** [comment]
http://cs.boisestate.edu/~dxu/research/MBT.html
